/**
 * Swagger API documentation for TODO Application
 * Swagger API documentation for TODO Application
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: rajaoarisoner@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { MouvementStckDto } from '../../src/app/model/mouvementStckDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MouvementStocksService {

    protected basePath = 'https://localhosthttp://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public correctionStockNegatif(body?: MouvementStckDto, observe?: 'body', reportProgress?: boolean): Observable<MouvementStckDto>;
    public correctionStockNegatif(body?: MouvementStckDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MouvementStckDto>>;
    public correctionStockNegatif(body?: MouvementStckDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MouvementStckDto>>;
    public correctionStockNegatif(body?: MouvementStckDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MouvementStckDto>(`${this.basePath}/api/mouvement/correctionNeg`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public correctionStockPositif(body?: MouvementStckDto, observe?: 'body', reportProgress?: boolean): Observable<MouvementStckDto>;
    public correctionStockPositif(body?: MouvementStckDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MouvementStckDto>>;
    public correctionStockPositif(body?: MouvementStckDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MouvementStckDto>>;
    public correctionStockPositif(body?: MouvementStckDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MouvementStckDto>(`${this.basePath}/api/mouvement/correctionPos`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public entreStock(body?: MouvementStckDto, observe?: 'body', reportProgress?: boolean): Observable<MouvementStckDto>;
    public entreStock(body?: MouvementStckDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MouvementStckDto>>;
    public entreStock(body?: MouvementStckDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MouvementStckDto>>;
    public entreStock(body?: MouvementStckDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MouvementStckDto>(`${this.basePath}/api/mouvement/entree`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param idArticle
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouvementStockArticle(idArticle: number, observe?: 'body', reportProgress?: boolean): Observable<Array<MouvementStckDto>>;
    public mouvementStockArticle(idArticle: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MouvementStckDto>>>;
    public mouvementStockArticle(idArticle: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MouvementStckDto>>>;
    public mouvementStockArticle(idArticle: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idArticle === null || idArticle === undefined) {
            throw new Error('Required parameter idArticle was null or undefined when calling mouvementStockArticle.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<MouvementStckDto>>(`${this.basePath}/api/mouvement/filtre/article/${encodeURIComponent(String(idArticle))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sortieStock(body?: MouvementStckDto, observe?: 'body', reportProgress?: boolean): Observable<MouvementStckDto>;
    public sortieStock(body?: MouvementStckDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MouvementStckDto>>;
    public sortieStock(body?: MouvementStckDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MouvementStckDto>>;
    public sortieStock(body?: MouvementStckDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MouvementStckDto>(`${this.basePath}/api/mouvement/sortie`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param idArticle
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stockReelArticle(idArticle: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public stockReelArticle(idArticle: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public stockReelArticle(idArticle: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public stockReelArticle(idArticle: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idArticle === null || idArticle === undefined) {
            throw new Error('Required parameter idArticle was null or undefined when calling stockReelArticle.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<number>(`${this.basePath}/api/mouvement/stockReel/${encodeURIComponent(String(idArticle))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
